### ISSUE TITLE
q = 12289

### ISSUE THREAD

**Issue by cothan** [ludopulles/hawk-sign#1]
Hi, 

I see in the paper, authors use prime q = 12289. 
May I know where is it used? 
I check the code but I didn't see such prime number. 

Best regards, 
Duc

**Comment by ludopulles** [comment]
Hi Duc,

The prime used in the main paper is `p = 2^{16} + 1`. However, 12289 or 18433 are also valid options (not resulting in an overflow during signing). You can find an implementation for the latter in the branch https://github.com/ludopulles/hawk-sign/tree/NTT-18433! It should be easily adoptable to 12289 as well.
